=== nookyo/app-manifest/src/app_manifest/schemas/application-manifest.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://qubership.org/schema/application.sbom.schema.json",
  "type": "object",
  "title": "Cloud application SBOM",
  "required": [
    "$schema",
    "bomFormat",
    "specVersion",
    "serialNumber",
    "version",
    "metadata",
    "components",
    "dependencies"
  ],
  "additionalProperties": false,
  "properties": {
    "$schema": { "type": "string" },
    "bomFormat": {
      "type": "string",
      "enum": ["CycloneDX"]
    },
    "specVersion": {
      "type": "string",
      "examples": ["1.6"]
    },
    "serialNumber": {
      "type": "string",
      "pattern": "^urn:uuid:[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    },
    "version": {
      "type": "integer",
      "minimum": 1,
      "default": 1
    },
    "metadata": {
      "$ref": "#/definitions/metadata-application"
    },
    "components": {
      "type": "array",
      "items": {
        "oneOf": [
          { "$ref": "#/definitions/application-component" },
          { "$ref": "#/definitions/helm-chart" },
          { "$ref": "#/definitions/docker-image" },
          { "$ref": "#/definitions/pipeline" },
          { "$ref": "#/definitions/zip-artifact" },
          { "$ref": "#/definitions/helm-values-schema" }
        ]
      },
      "uniqueItems": true
    },
    "dependencies": {
      "type": "array",
      "items": { "$ref": "#/definitions/dependency" },
      "uniqueItems": true
    }
  },
  "definitions": {
    "refLinkType": {
      "$ref": "#/definitions/refType"
    },
    "refType": {
      "type": "string",
      "minLength": 1
    },
    "version": {
      "type": "string",
      "maxLength": 1024
    },
    "dependency": {
      "type": "object",
      "required": ["ref", "dependsOn"],
      "additionalProperties": false,
      "properties": {
        "ref": { "$ref": "#/definitions/refLinkType" },
        "dependsOn": {
          "type": "array",
          "uniqueItems": true,
          "items": { "$ref": "#/definitions/refLinkType" }
        }
      }
    },
    "attachment": {
      "type": "object",
      "required": ["content"],
      "additionalProperties": false,
      "properties": {
        "contentType": { "type": "string" },
        "encoding": { "type": "string", "enum": ["base64"] },
        "content": { "type": "string" }
      }
    },
    "hash": {
      "type": "object",
      "required": ["alg", "content"],
      "additionalProperties": false,
      "properties": {
        "alg": { "$ref": "#/definitions/hash-alg" },
        "content": { "$ref": "#/definitions/hash-content" }
      }
    },
    "hash-alg": {
      "type": "string",
      "enum": ["MD5","SHA-1","SHA-256","SHA-384","SHA-512","SHA3-256","SHA3-384","SHA3-512","BLAKE2b-256","BLAKE2b-384","BLAKE2b-512","BLAKE3"]
    },
    "hash-content": {
      "type": "string",
      "pattern": "^([a-fA-F0-9]{32}|[a-fA-F0-9]{40}|[a-fA-F0-9]{64}|[a-fA-F0-9]{96}|[a-fA-F0-9]{128})$"
    },
    "metadata-application": {
      "type": "object",
      "required": ["timestamp", "component", "tools"],
      "additionalProperties": false,
      "properties": {
        "timestamp": { "type": "string", "format": "date-time" },
        "component": {
          "type": "object",
          "required": ["type", "mime-type", "bom-ref", "name", "version"],
          "additionalProperties": false,
          "properties": {
            "type": { "type": "string", "enum": ["application"] },
            "mime-type": { "type": "string", "enum": ["application/vnd.nc.application"] },
            "bom-ref": { "$ref": "#/definitions/refType" },
            "name": { "type": "string" },
            "version": { "$ref": "#/definitions/version" }
          }
        },
        "tools": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "components": {
              "type": "array",
              "items": {
                "type": "object",
                "required": ["type", "name", "version"],
                "additionalProperties": false,
                "properties": {
                  "type": { "type": "string", "enum": ["application"] },
                  "name": { "type": "string" },
                  "version": { "$ref": "#/definitions/version" }
                }
              },
              "uniqueItems": true
            }
          }
        }
      }
    },
    "docker-image": {
      "type": "object",
      "required": ["type", "mime-type", "bom-ref", "group", "name", "version", "purl"],
      "additionalProperties": false,
      "properties": {
        "type": { "type": "string", "enum": ["container"] },
        "mime-type": { "type": "string", "enum": ["application/vnd.docker.image"] },
        "bom-ref": { "$ref": "#/definitions/refType" },
        "group": { "type": "string" },
        "name": { "type": "string" },
        "version": { "$ref": "#/definitions/version" },
        "hashes": { "type": "array", "items": { "$ref": "#/definitions/hash" } },
        "purl": { "type": "string" },
        "properties": {
          "type": "array",
          "items": {
            "type": "object",
            "required": ["name", "value"],
            "additionalProperties": false,
            "properties": {
              "name": { "type": "string" },
              "value": { "oneOf": [{"type": "string"}, {"type": "array"}, {"type": "object"}, {"type": "boolean"}] }
            }
          }
        }
      }
    },
    "pipeline": {
      "type": "object",
      "required": ["type", "mime-type", "bom-ref", "name"],
      "additionalProperties": false,
      "properties": {
        "type": { "type": "string", "enum": ["data"] },
        "mime-type": { "type": "string", "enum": ["application/vnd.nc.standalone-runnable"] },
        "bom-ref": { "$ref": "#/definitions/refType" },
        "name": { "type": "string" },
        "version": { "$ref": "#/definitions/version" },
        "properties": {
          "type": "array",
          "items": {
            "type": "object",
            "required": ["name", "value"],
            "additionalProperties": false,
            "properties": {
              "name": { "type": "string" },
              "value": { "oneOf": [{"type": "string"}, {"type": "array"}, {"type": "object"}, {"type": "boolean"}] }
            }
          }
        },
        "components": {
          "type": "array",
          "items": {
            "oneOf": [
              { "$ref": "#/definitions/zip-artifact" },
              { "$ref": "#/definitions/docker-image" }
            ]
          },
          "uniqueItems": true
        }
      }
    },
    "zip-artifact": {
      "type": "object",
      "required": ["type", "mime-type", "bom-ref", "group", "name", "version", "hashes", "purl"],
      "additionalProperties": false,
      "properties": {
        "type": { "type": "string", "enum": ["data"] },
        "mime-type": { "type": "string", "enum": ["application/zip"] },
        "bom-ref": { "$ref": "#/definitions/refType" },
        "group": { "type": "string" },
        "name": { "type": "string" },
        "version": { "$ref": "#/definitions/version" },
        "hashes": { "type": "array", "items": { "$ref": "#/definitions/hash" } },
        "purl": { "type": "string" },
        "properties": {
          "type": "array",
          "items": {
            "type": "object",
            "required": ["name", "value"],
            "additionalProperties": false,
            "properties": {
              "name": { "type": "string" },
              "value": { "oneOf": [{"type": "string"}, {"type": "array"}, {"type": "object"}, {"type": "boolean"}] }
            }
          }
        }
      }
    },
    "resource-profile-baseline": {
      "type": "object",
      "required": ["type", "mime-type", "bom-ref", "name", "data"],
      "additionalProperties": false,
      "properties": {
        "type": { "type": "string", "enum": ["data"] },
        "mime-type": { "type": "string", "enum": ["application/vnd.nc.resource-profile-baseline"] },
        "bom-ref": { "$ref": "#/definitions/refType" },
        "name": { "type": "string", "const": "resource-profile-baselines" },
        "data": {
          "type": "array",
          "items": {
            "type": "object",
            "required": ["type", "name", "contents"],
            "additionalProperties": false,
            "properties": {
              "type": { "type": "string", "enum": ["configuration"] },
              "name": { "type": "string" },
              "contents": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                  "attachment": { "$ref": "#/definitions/attachment" }
                }
              }
            }
          }
        }
      }
    },
    "helm-values-schema": {
      "type": "object",
      "required": ["type", "mime-type", "bom-ref", "name", "data"],
      "additionalProperties": false,
      "properties": {
        "type": { "type": "string", "enum": ["data"] },
        "mime-type": { "type": "string", "enum": ["application/vnd.nc.helm.values.schema"] },
        "bom-ref": { "$ref": "#/definitions/refType" },
        "name": { "type": "string" },
        "data": {
          "type": "array",
          "items": {
            "type": "object",
            "required": ["type", "name", "contents"],
            "additionalProperties": false,
            "properties": {
              "type": { "type": "string", "enum": ["configuration"] },
              "name": { "type": "string" },
              "contents": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                  "attachment": { "$ref": "#/definitions/attachment" }
                }
              }
            }
          }
        }
      }
    },
    "helm-chart": {
      "type": "object",
      "required": ["type", "mime-type", "bom-ref", "name", "properties", "components"],
      "additionalProperties": false,
      "properties": {
        "type": { "type": "string", "enum": ["application"] },
        "mime-type": { "type": "string", "enum": ["application/vnd.nc.helm.chart"] },
        "bom-ref": { "$ref": "#/definitions/refType" },
        "name": { "type": "string" },
        "version": { "$ref": "#/definitions/version" },
        "hashes": { "type": "array", "items": { "$ref": "#/definitions/hash" } },
        "purl": { "type": "string" },
        "properties": {
          "type": "array",
          "items": {
            "type": "object",
            "required": ["name", "value"],
            "additionalProperties": false,
            "properties": {
              "name": { "type": "string" },
              "value": { "oneOf": [{"type": "string"}, {"type": "array"}, {"type": "object"}, {"type": "boolean"}] }
            }
          }
        },
        "components": {
          "type": "array",
          "items": {
            "anyOf": [
              { "$ref": "#/definitions/helm-chart" },
              { "$ref": "#/definitions/helm-values-schema" },
              { "$ref": "#/definitions/resource-profile-baseline" }
            ]
          },
          "uniqueItems": true
        }
      }
    },
    "application-component": {
      "type": "object",
      "required": ["type", "mime-type", "bom-ref", "name", "properties", "components"],
      "additionalProperties": false,
      "properties": {
        "type": { "type": "string", "enum": ["application"] },
        "mime-type": { "type": "string", "enum": ["application/vnd.nc.standalone-runnable"] },
        "bom-ref": { "$ref": "#/definitions/refType" },
        "name": { "type": "string" },
        "version": { "$ref": "#/definitions/version" },
        "properties": {
          "type": "array",
          "items": {
            "type": "object",
            "required": ["name", "value"],
            "additionalProperties": false,
            "properties": {
              "name": { "type": "string" },
              "value": { "oneOf": [{"type": "string"}, {"type": "array"}, {"type": "object"}, {"type": "boolean"}] }
            }
          }
        },
        "components": {
          "type": "array",
          "uniqueItems": true,
          "maxItems": 0
        }
      }
    }
  }
}

=== nookyo/app-manifest/tests/fixtures/examples/example_jaeger_manifest.json
{
  "serialNumber": "urn:uuid:8079847f-20f2-4f2f-9c12-f85fca0e1597",
  "$schema": "../schemas/application-manifest.schema.json",
  "bomFormat": "CycloneDX",
  "specVersion": "1.6",
  "version": 1,
  "metadata": {
    "timestamp": "2026-02-18T08:05:06Z",
    "component": {
      "bom-ref": "qubership-jaeger:37f82636-abed-4e20-8273-81f25bec4de7",
      "type": "application",
      "mime-type": "application/vnd.nc.application",
      "name": "qubership-jaeger",
      "version": "1.2.3"
    },
    "tools": {
      "components": [
        {
          "type": "application",
          "name": "am-build-cli",
          "version": "0.1.0"
        }
      ]
    }
  },
  "components": [
    {
      "bom-ref": "qubership-jaeger:e1133017-fd1e-4bdd-845e-2f66e8decea7",
      "type": "application",
      "mime-type": "application/vnd.nc.standalone-runnable",
      "name": "qubership-jaeger",
      "version": "1.2.3",
      "properties": [],
      "components": []
    },
    {
      "bom-ref": "qubership-jaeger:230982d3-7068-48c2-8666-070406d8d59e",
      "type": "application",
      "mime-type": "application/vnd.nc.helm.chart",
      "name": "qubership-jaeger",
      "version": "1.2.3",
      "purl": "pkg:helm/charts/qubership-jaeger@1.2.3?registry_name=sandbox.example.com",
      "properties": [
        {
          "name": "isLibrary",
          "value": false
        },
        {
          "name": "qubership:helm.values.artifactMappings",
          "value": {
            "jaeger:7ab2a95a-852b-46aa-ab34-4e1a9ba14726": {
              "valuesPathPrefix": "images.jaeger"
            },
            "envoy:4ce2de41-c8d8-4970-aef7-72761d77a485": {
              "valuesPathPrefix": "images.envoy"
            }
          }
        }
      ],
      "hashes": [
        {
          "alg": "SHA-256",
          "content": "b8843624c985879af20ea831ea2ff29698ec128e7a34e13bda0b432b901c6fc9"
        }
      ],
      "components": [
        {
          "bom-ref": "values.schema.json:89532557-3f65-4230-8203-e3b98c79cb30",
          "type": "data",
          "mime-type": "application/vnd.nc.helm.values.schema",
          "name": "values.schema.json",
          "data": [
            {
              "type": "configuration",
              "name": "values.schema.json",
              "contents": {
                "attachment": {
                  "contentType": "application/json",
                  "encoding": "base64",
                  "content": "eyJ0eXBlIjogIm9iamVjdCIsICJwcm9wZXJ0aWVzIjoge319"
                }
              }
            }
          ]
        }
      ]
    },
    {
      "bom-ref": "jaeger:7ab2a95a-852b-46aa-ab34-4e1a9ba14726",
      "type": "container",
      "mime-type": "application/vnd.docker.image",
      "name": "jaeger",
      "version": "build3",
      "group": "core",
      "purl": "pkg:docker/core/jaeger@build3?registry_name=sandbox.example.com",
      "hashes": [
        {
          "alg": "SHA-256",
          "content": "a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2"
        }
      ]
    },
    {
      "bom-ref": "envoy:4ce2de41-c8d8-4970-aef7-72761d77a485",
      "type": "container",
      "mime-type": "application/vnd.docker.image",
      "name": "envoy",
      "version": "v1.32.6",
      "group": "envoyproxy",
      "purl": "pkg:docker/envoyproxy/envoy@v1.32.6?registry_name=ghcr.io",
      "hashes": [
        {
          "alg": "SHA-256",
          "content": "a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6b2c3"
        }
      ]
    }
  ],
  "dependencies": [
    {
      "ref": "qubership-jaeger:37f82636-abed-4e20-8273-81f25bec4de7",
      "dependsOn": [
        "qubership-jaeger:e1133017-fd1e-4bdd-845e-2f66e8decea7",
        "qubership-jaeger:230982d3-7068-48c2-8666-070406d8d59e",
        "jaeger:7ab2a95a-852b-46aa-ab34-4e1a9ba14726",
        "envoy:4ce2de41-c8d8-4970-aef7-72761d77a485"
      ]
    },
    {
      "ref": "qubership-jaeger:e1133017-fd1e-4bdd-845e-2f66e8decea7",
      "dependsOn": [
        "qubership-jaeger:230982d3-7068-48c2-8666-070406d8d59e"
      ]
    },
    {
      "ref": "qubership-jaeger:230982d3-7068-48c2-8666-070406d8d59e",
      "dependsOn": [
        "jaeger:7ab2a95a-852b-46aa-ab34-4e1a9ba14726",
        "envoy:4ce2de41-c8d8-4970-aef7-72761d77a485"
      ]
    }
  ]
}

=== nookyo/app-manifest/tests/fixtures/examples/jaeger_manifest.json
{
  "serialNumber": "urn:uuid:2ff5412e-5ff9-4d93-9702-9d3b2c2a92c5",
  "$schema": "../schemas/application-manifest.schema.json",
  "bomFormat": "CycloneDX",
  "specVersion": "1.6",
  "version": 1,
  "metadata": {
    "timestamp": "2026-03-11T06:31:16Z",
    "component": {
      "bom-ref": "jaeger:9e5221cf-07ac-4aea-b65c-3efe61364d2e",
      "type": "application",
      "mime-type": "application/vnd.nc.application",
      "name": "jaeger",
      "version": "1.2.3"
    },
    "tools": {
      "components": [
        {
          "type": "application",
          "name": "am-build-cli",
          "version": "0.1.0"
        }
      ]
    }
  },
  "components": [
    {
      "bom-ref": "qubership-jaeger:b6ae6074-ebc9-41a3-abe0-13ffb61366f4",
      "type": "application",
      "mime-type": "application/vnd.nc.standalone-runnable",
      "name": "qubership-jaeger",
      "version": "1.2.3",
      "properties": [],
      "components": []
    },
    {
      "bom-ref": "qubership-jaeger:60ef6d01-3824-403e-8e80-9ada9423aad6",
      "type": "application",
      "mime-type": "application/vnd.nc.helm.chart",
      "name": "qubership-jaeger",
      "version": "1.2.3",
      "purl": "pkg:helm/charts/qubership-jaeger@1.2.3?registry_name=sandbox.example.com",
      "properties": [
        {
          "name": "isLibrary",
          "value": false
        },
        {
          "name": "qubership:helm.values.artifactMappings",
          "value": {
            "jaeger-cassandra-schema:fc1bf1f0-9b7e-46b9-81ac-719474e32185": {
              "valuesPathPrefix": "cassandraSchema"
            },
            "jaeger:510e3687-f84b-4b82-ba64-2d61b4067146": {
              "valuesPathPrefix": "jaeger"
            },
            "jaeger-readiness-probe:8720e173-b2ea-4e72-b0eb-573cdd824f7a": {
              "valuesPathPrefix": "readinessProbe"
            },
            "example-hotrod:f9a057a2-ac80-44f1-8e65-2687f6636a8e": {
              "valuesPathPrefix": "exampleHotrod"
            },
            "jaeger-integration-tests:f2d8485e-be62-401a-9b2f-f451ca538d2e": {
              "valuesPathPrefix": "integrationTests"
            },
            "jaeger-es-index-cleaner:2b9fb8bf-fd5c-42ad-bced-7731e5d6b3b9": {
              "valuesPathPrefix": "elasticsearch.indexCleaner"
            },
            "jaeger-es-rollover:8ee2ed43-3b40-4b41-9b81-8598efcf2962": {
              "valuesPathPrefix": "elasticsearch.rollover"
            },
            "envoy:7165f9d1-a659-4274-8b1f-d92da5142af6": {
              "valuesPathPrefix": "proxy"
            },
            "openjdk:790b7a29-1975-4ea1-b81a-7fefa3b3a0d1": {
              "valuesPathPrefix": "."
            },
            "spark-dependencies-image:9bc28474-c783-497b-b6ac-609a2a4d9937": {
              "valuesPathPrefix": "spark"
            },
            "qubership-deployment-status-provisioner:30c25afc-b313-4649-a486-397ffe35e591": {
              "valuesPathPrefix": "statusProvisioner"
            }
          }
        }
      ],
      "hashes": [
        {
          "alg": "SHA-256",
          "content": "c01ce70d91b920226bc4f788849a85127b3f49ea4af5db4012c2ce8def0d79e1"
        }
      ],
      "components": []
    },
    {
      "bom-ref": "jaeger-cassandra-schema:fc1bf1f0-9b7e-46b9-81ac-719474e32185",
      "type": "container",
      "mime-type": "application/vnd.docker.image",
      "name": "jaeger-cassandra-schema",
      "version": "1.72.0",
      "group": "jaegertracing",
      "purl": "pkg:docker/jaegertracing/jaeger-cassandra-schema@1.72.0?registry_name=docker.io"
    },
    {
      "bom-ref": "jaeger:510e3687-f84b-4b82-ba64-2d61b4067146",
      "type": "container",
      "mime-type": "application/vnd.docker.image",
      "name": "jaeger",
      "version": "2.9.0",
      "group": "jaegertracing",
      "purl": "pkg:docker/jaegertracing/jaeger@2.9.0?registry_name=docker.io"
    },
    {
      "bom-ref": "example-hotrod:f9a057a2-ac80-44f1-8e65-2687f6636a8e",
      "type": "container",
      "mime-type": "application/vnd.docker.image",
      "name": "example-hotrod",
      "version": "1.72.0",
      "group": "jaegertracing",
      "purl": "pkg:docker/jaegertracing/example-hotrod@1.72.0?registry_name=docker.io"
    },
    {
      "bom-ref": "jaeger-es-index-cleaner:2b9fb8bf-fd5c-42ad-bced-7731e5d6b3b9",
      "type": "container",
      "mime-type": "application/vnd.docker.image",
      "name": "jaeger-es-index-cleaner",
      "version": "1.72.0",
      "group": "jaegertracing",
      "purl": "pkg:docker/jaegertracing/jaeger-es-index-cleaner@1.72.0?registry_name=docker.io"
    },
    {
      "bom-ref": "jaeger-es-rollover:8ee2ed43-3b40-4b41-9b81-8598efcf2962",
      "type": "container",
      "mime-type": "application/vnd.docker.image",
      "name": "jaeger-es-rollover",
      "version": "1.72.0",
      "group": "jaegertracing",
      "purl": "pkg:docker/jaegertracing/jaeger-es-rollover@1.72.0?registry_name=docker.io"
    },
    {
      "bom-ref": "envoy:7165f9d1-a659-4274-8b1f-d92da5142af6",
      "type": "container",
      "mime-type": "application/vnd.docker.image",
      "name": "envoy",
      "version": "v1.32.6",
      "group": "envoyproxy",
      "purl": "pkg:docker/envoyproxy/envoy@v1.32.6?registry_name=docker.io"
    },
    {
      "bom-ref": "openjdk:790b7a29-1975-4ea1-b81a-7fefa3b3a0d1",
      "type": "container",
      "mime-type": "application/vnd.docker.image",
      "name": "openjdk",
      "version": "11",
      "group": "library",
      "purl": "pkg:docker/library/openjdk@11?registry_name=docker.io"
    },
    {
      "bom-ref": "jaeger-readiness-probe:8720e173-b2ea-4e72-b0eb-573cdd824f7a",
      "type": "container",
      "mime-type": "application/vnd.docker.image",
      "name": "jaeger-readiness-probe",
      "version": "1.2.3",
      "group": "qubership",
      "purl": "pkg:docker/qubership/jaeger-readiness-probe@1.2.3?registry_name=sandbox.example.com",
      "hashes": [
        {
          "alg": "SHA-256",
          "content": "a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1"
        }
      ]
    },
    {
      "bom-ref": "jaeger-integration-tests:f2d8485e-be62-401a-9b2f-f451ca538d2e",
      "type": "container",
      "mime-type": "application/vnd.docker.image",
      "name": "jaeger-integration-tests",
      "version": "1.2.3",
      "group": "qubership",
      "purl": "pkg:docker/qubership/jaeger-integration-tests@1.2.3?registry_name=sandbox.example.com",
      "hashes": [
        {
          "alg": "SHA-256",
          "content": "b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2"
        }
      ]
    },
    {
      "bom-ref": "spark-dependencies-image:9bc28474-c783-497b-b6ac-609a2a4d9937",
      "type": "container",
      "mime-type": "application/vnd.docker.image",
      "name": "spark-dependencies-image",
      "version": "1.2.3",
      "group": "qubership",
      "purl": "pkg:docker/qubership/spark-dependencies-image@1.2.3?registry_name=sandbox.example.com",
      "hashes": [
        {
          "alg": "SHA-256",
          "content": "c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3"
        }
      ]
    },
    {
      "bom-ref": "qubership-deployment-status-provisioner:30c25afc-b313-4649-a486-397ffe35e591",
      "type": "container",
      "mime-type": "application/vnd.docker.image",
      "name": "qubership-deployment-status-provisioner",
      "version": "1.2.3",
      "group": "qubership",
      "purl": "pkg:docker/qubership/qubership-deployment-status-provisioner@1.2.3?registry_name=sandbox.example.com",
      "hashes": [
        {
          "alg": "SHA-256",
          "content": "d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4"
        }
      ]
    }
  ],
  "dependencies": [
    {
      "ref": "jaeger:9e5221cf-07ac-4aea-b65c-3efe61364d2e",
      "dependsOn": [
        "qubership-jaeger:b6ae6074-ebc9-41a3-abe0-13ffb61366f4",
        "qubership-jaeger:60ef6d01-3824-403e-8e80-9ada9423aad6",
        "jaeger-cassandra-schema:fc1bf1f0-9b7e-46b9-81ac-719474e32185",
        "jaeger:510e3687-f84b-4b82-ba64-2d61b4067146",
        "example-hotrod:f9a057a2-ac80-44f1-8e65-2687f6636a8e",
        "jaeger-es-index-cleaner:2b9fb8bf-fd5c-42ad-bced-7731e5d6b3b9",
        "jaeger-es-rollover:8ee2ed43-3b40-4b41-9b81-8598efcf2962",
        "envoy:7165f9d1-a659-4274-8b1f-d92da5142af6",
        "openjdk:790b7a29-1975-4ea1-b81a-7fefa3b3a0d1",
        "jaeger-readiness-probe:8720e173-b2ea-4e72-b0eb-573cdd824f7a",
        "jaeger-integration-tests:f2d8485e-be62-401a-9b2f-f451ca538d2e",
        "spark-dependencies-image:9bc28474-c783-497b-b6ac-609a2a4d9937",
        "qubership-deployment-status-provisioner:30c25afc-b313-4649-a486-397ffe35e591"
      ]
    },
    {
      "ref": "qubership-jaeger:b6ae6074-ebc9-41a3-abe0-13ffb61366f4",
      "dependsOn": [
        "qubership-jaeger:60ef6d01-3824-403e-8e80-9ada9423aad6"
      ]
    },
    {
      "ref": "qubership-jaeger:60ef6d01-3824-403e-8e80-9ada9423aad6",
      "dependsOn": [
        "jaeger-cassandra-schema:fc1bf1f0-9b7e-46b9-81ac-719474e32185",
        "jaeger:510e3687-f84b-4b82-ba64-2d61b4067146",
        "jaeger-readiness-probe:8720e173-b2ea-4e72-b0eb-573cdd824f7a",
        "example-hotrod:f9a057a2-ac80-44f1-8e65-2687f6636a8e",
        "jaeger-integration-tests:f2d8485e-be62-401a-9b2f-f451ca538d2e",
        "jaeger-es-index-cleaner:2b9fb8bf-fd5c-42ad-bced-7731e5d6b3b9",
        "jaeger-es-rollover:8ee2ed43-3b40-4b41-9b81-8598efcf2962",
        "envoy:7165f9d1-a659-4274-8b1f-d92da5142af6",
        "openjdk:790b7a29-1975-4ea1-b81a-7fefa3b3a0d1",
        "spark-dependencies-image:9bc28474-c783-497b-b6ac-609a2a4d9937",
        "qubership-deployment-status-provisioner:30c25afc-b313-4649-a486-397ffe35e591"
      ]
    }
  ]
}
